defaults:
  script: db.sql

logging:
  level: SQL

database: postgresql://localhost:5432/eav_db?user=postgres&password=postgres

API:
  help:
    type: self
    function: api_help

  enum_get:
    type: db
    function: meta.enum_get
    help: |
      Возвращает список перечислений (если не задан ключ) или перечисление
      {
         "key": "ключ перечисления"
      }

  sheet_type_set:
    type: db
    function: meta.sheet_set
    help: |
      {
        "up_version": "булевый флаг, признак того что нужно создать версию при редактировании. по умолчанию true",
        "guid": "идентификатор документа",
        "version_guid": "идентификатор версии, в которую писать",
        "title": "название документа",
        ?"has_version": "признак того, что документ версионируется. по умолчанию - true",
        ?"mac_mode": "-2 любая метка -1 первая введенная 0..3 заданная",
        ?"force": "если задан и = true, то отключается проверка  на наличие данных в удаляемой колонке",
        "columns": [
          {
            "delete": "признак того, что поле нужно удалить, это можно сделать до вызова document_check. умолчание - false",
            "name": "имя поля в БД (обязательное поле)",
            "new_name": "новое имя атрибута. используется для переименования",
            "title": "название поля для пользователя (обязательное поле)",
            "type": "код типа поля. по умолчанию - строка",
            "tooltip": "подсказка к полю",
            "reference": "для типа <R> - guid таблицы, на которую делаем ссылку, 
                          для типа <r> - имя поля данной таблицы, которое описывает ссылку (R), 
                          для типа <E> - код идентификатор перечисления",
            "reference_guid": "!! для совместимости. вместо этого использовать параметр reference",
            ?"reference_class": "позволяет задать класс записей (с потомками) на который можно ссылаться. ксли задан reference_guid игнорируется",
            "reference_column": "атрибут значение которого будет взято по ссылке",
            "reference_names": "!! для совместимости. вместо этого использовать параметр reference_column. массив в первом элементе которого находится reference_column",
            "order": "порядковый номер поля в выборке",
            "reg_expr": "регулярное выражение для проверки значений",
            "is_unique": "признак уникальности поля. умолчание false",
            "is_nullable": "разрешение пустых полей. умолчание true",
            "size": "размер поля для строк и вещественных. для вещественных можно ввести через точку - символы и дробную часть",
            "is_editable": "разрешает/запрещает редактирование поля на клиенте",
            "is_visible": "определяет видимость поля",
            "is_calculated": "служит для указание того, что поле хранится только заголовок поля, но данные не добавляюся в БД",
            "item_type": " значения какого типа лежат в массиве 
                                S - строка
                                I - целое
                                F - вещественное
                                B - булевое
                               или дате/времени (то же может лежать в массивах)   
                                D - дата
                                T - время
                                W - дата и время (when)
                               подтипы для строк и текста
                                A - с автоматическим распознаванием base64 на входе. на выходе - без перекодирования
                                B - с ожиданием base64 на входе. и выводом base64 на выходе в режиме R sheet_get
                            для перечеслимых полей в item_type задается имя перечисления"
          }
        ]
      }
      

  sheet_type_get:
    type: db
    function: meta.sheet_get
    help: |
      возвращает метаданные таблицы по её идентификатору или идентификатору её версии
      {
        "guid": "идентификатор таблицы",
        "version_guid": "идентификатор версии"
      }
        

  sheet_set:
    type: db
    function: data.sheet_set
    help: |
      {
          "guid": "идентификатор страницы",
          "table": "уникальное имя таблицы, если задано при описании таблицы, то по нему можно таблицу найти (вместо guid)",
          "class_guid": "если задан, то таблицу берем по нему и пишем только атрибуты, относящиеся к классу",
          "key_search": "булевый. если включен, то при отсутствии ключа записи идет поиск записи по уникальным полям.
                        по умолчанию выключен",
          "skip_read_only": "если true, то значения is_editable:false полей автоматически не ставятся. умолчание false",
          "rows": [
              {
                  "guid": "идентификатор строки",
                  "delete": "признак того, что строку надо удалить: false (строку удалять не нужно) или true(строку нужно удалить); по умолчанию - false", 
                  "data": {
                  объект, содержащий описание изменяемых объектов
                      "имя атрибута 1": "значение атрибута 1",
                      ...
                      "имя атрибута N": "значение атрибута N"
                  }
              },
          ]
      }

  sheet_get: # имя метода в API
    function: data.sheet_get # имя функции, реализующей метод
    type: db # тип функции: db - функция в БД, self - функция в классе сервиса, py - функция в плагине
    help: |
      Возвращает данные страницы
      {
        "guid": "идентификатор страницы",
        "table": "уникальное имя таблицы, если задано при описании таблицы, то по нему можно таблицу найти (вместо guid)",
        "class_guid": "если задан, то таблицу берем по нему и выбираем только дочерние классы",
        "version_guid": "требуемая версия страницы",
        "current_mac_only": "флаг отбора данных по текущей мандатной метке. по умолчанию false [все доступные метки]",
        "limit": "количество записей на странице",
        "offset": "смещение первой записи на странице от начала списка",
        "distinct": "указывает, что нужно отобразить только уникальные записи. по умолчанию false. если включен, то отменяет limit и offset",
        "ref_name_mode": "если задан и
                    1 - для ссылочных атрибутов выводится значение первого имени, без массива
                    R - в ссылочные атрибуты выводятся значения ссылок (зеркально sheet_set)
                    F - поля выводятся без группировки в структуры data и references",
        "fields": [массив полей, значения которых нужно вернуть. если не задан - вернутся все поля],
        "level_by": "для иерархических таблиц принимает на вход имя поля, по которому нужно построить 
                     иерархию. при этом на выходе у записей появляются атрибуты level - уровень вложенности и 
                     childs - количество вложений",
        "filter": [ 
        массив с описанием примененной фильтрации, правило фильтра может быть передано в двух вариантах
          {"имя поля":"значение"},
          или
          {"имя поля":"значение", "":"знак операции"},
          ...
        ],
        "order": [
        массив с описанием сортировки
            {"имя поля объекта":"порядок сортировки записей поля: asc (по возрастанию) или desc (по убыванию); по умолчанию - asc"}
            ...
            ]
      }