defaults:
  script: db.sql
database: postgresql://localhost:5432/eav_db?user=postgres&password=postgres
API:
  sheet_type_set:
    type: db
    function: meta.sheet_set
    help: |
      {
        "up_version": "булевый флаг, признак того что нужно создать версию при редактировании. по умолчанию true",
        "guid": "идентификатор документа",
        "title": "название документа",
        ?"has_version": "признак того, что документ версионируется. по умолчанию - true",
        ?"mac_mode": "-2 любая метка -1 первая введенная 0..3 заданная",
        ?"force": "если задан и = true, то отключается проверка  на наличие данных в удаляемой колонке",
        "columns": [
          {
            "delete": "признак того, что поле нужно удалить, это можно сделать до вызова document_check. умолчание - false",
            "name": "имя поля в БД (обязательное поле)",
            "new_name": "новое имя атрибута. используется для переименования",
            "title": "название поля для пользователя (обязательное поле)",
            "type": "код типа поля. по умолчанию - строка",
            "tooltip": "подсказка к полю",
            "reference_guid": "на какой документ ссылается поле. если задано - type игнорируется. для перечислимых полей - guid перечисленияы",
            "reference_class": "позволяет задать класс записей (с потомками) на который можно ссылаться. ксли задан reference_guid игнорируется",
            "reference_names": "массив со списком именующих полей для ссылки",
            "order": "порядковый номер поля в выборке",
            "reg_expr": "регулярное выражение для проверки значений",
            "is_unique": "признак уникальности поля. умолчание false",
            "is_nullable": "разрешение пустых полей. умолчание true",
            "size": "размер поля для строк и вещественных. для вещественных можно ввести через точку - символы и дробную часть",
            "is_editable": "разрешает/запрещает редактирование поля на клиенте",
            "is_visible": "определяет видимость поля",
            "is_calculated": "служит для указание того, что поле хранится только заголовок поля, но данные не добавляюся в БД",
            "item_type": " значения какого типа лежат в массиве 
                                S - строка
                                I - целое
                                F - вещественное
                                B - булевое
                               или дате/времени (то же может лежать в массивах)   
                                D - дата
                                T - время
                                W - дата и время (when)
                               подтипы для строк и текста
                                A - с автоматическим распознаванием base64 на входе. на выходе - без перекодирования
                                B - с ожиданием base64 на входе. и выводом base64 на выходе в режиме R sheet_get
                            для перечеслимых полей в item_type задается имя перечисления"
          }
        ]
      }
